version: '19'

services:
  db:
    container_name: 'database-node'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'order_manager'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
